name: Integration tests

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Install crypto library libsodium
        run: sudo apt install libsodium-dev

      - name: Check out code
        uses: actions/checkout@v2

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Cmake
        run: cmake .

      - name: Build
        run: cmake --build .

      - name: Integration Tests - new testnet
        run: cd scripts && /bin/bash local-testnet.sh new

      - name: Integration Tests - testnet start
        run: cd scripts && /bin/bash local-testnet.sh start

      - name: IntegrationTests - run tests
        run: cd scripts && /bin/bash test-with-proxy.sh
        continue-on-error: true

      - name: Integration Tests - testnet stop
        run: cd scripts && /bin/bash local-testnet.sh stop
