name: Tests

on:
  push:
    branches: [ development, main, feat/* ]
  pull_request:
    branches: [ development, main, feat/* ]

jobs:
  test:
    name: Unit
    runs-on: ubuntu-latest
    steps:
      - name: Install crypto library libsodium
        run: sudo apt install libsodium-dev

      - name: Check out code
        uses: actions/checkout@v2

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Build
        run:
          cmake .
          cmake --build .

      - name: Unit tests
        run: ./scripts.sh