name: Unit tests

on:
  push:
    branches: [ development, main, feat/* ]
  pull_request:
    branches: [ development, main, feat/* ]

jobs:
  call-build:
    uses: ./.github/workflows/build.yml
  test:
    needs: call-build
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Unit Tests
        run: ./scripts.sh
